apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    name: flask
spec:
  type: NodePort
  ports:
    - nodePort: {{.Values.nodeport.port}}
      port: 8080
      targetPort: 8080
  selector:
    app: flask