name: Build step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_REPO: yelyzavetazhyrova/helm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get image tag with short sha
        id: image_tag
        run: echo "image_tag=$DOCKER_HUB_REPO:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          docker build . --file Dockerfile --tag ${{ steps.image_tag.outputs.image_tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        run: docker push ${{ steps.image_tag.outputs.image_tag }}
