name: Build step

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          echo "IMAGE_TAG=yelyzavetazhyrova/helm:$(date +%s)" >> $GITHUB_ENV
          docker build . --file Dockerfile --tag ${{env.IMAGE_TAG}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        run: docker push ${{env.IMAGE_TAG}}
